### ISSUE TITLE
FIX-003: Update activate and deactivate methods

### ISSUE THREAD

**Issue by meirlustig1983** [meirlustig1983/bank-management#102]
### TASKS:
- [x] **Active Method**
   - [x] If the account is inactive, activate the account
   - [x] If the account is active, return the original data
- [x] **Deactive Method**
   - [x] If the account is active, deactivate the account
   - [x] If the account is inactive, return the original data
- [x] Tests
